import type { DashboardData } from "@/lib/types";

const companyId = "biz_demo";
const now = Date.now();
const hours = (n: number) => new Date(now + n * 3_600_000).toISOString();

export const demoData: DashboardData = {
  companyId,
  demo: true,
  emergencyPaused: false,
  settings: {
    emergency_paused: false,
    default_timezone: "America/Chicago",
    support_contact: "support@scaledcreators.com",
    display_name: "Coaching Bookings",
    logo_url: null,
    theme_name: "Orange",
    theme_primary: "#ff4b18",
    theme_accent: "#a84a32",
    theme_highlight: "#ff7849",
  },
  availability: [1, 2, 3, 4, 5].flatMap((weekday) => [
    {
      id: `rule_graham_${weekday}`,
      whop_company_id: companyId,
      coach_id: "coach_graham",
      offer_id: null,
      weekday,
      start_time: "09:00:00",
      end_time: "17:00:00",
      timezone: "America/Chicago",
      status: "active" as const,
    },
    {
      id: `rule_maya_${weekday}`,
      whop_company_id: companyId,
      coach_id: "coach_maya",
      offer_id: null,
      weekday,
      start_time: "10:00:00",
      end_time: "16:00:00",
      timezone: "America/Chicago",
      status: "active" as const,
    },
  ]),
  coaches: [
    {
      id: "coach_graham",
      whop_company_id: companyId,
      name: "Graham Lee",
      bio: "Growth strategy and creator systems",
      timezone: "America/Chicago",
      status: "active",
    },
    {
      id: "coach_maya",
      whop_company_id: companyId,
      name: "Maya Chen",
      bio: "Offer positioning and conversion",
      timezone: "America/Chicago",
      status: "active",
    },
  ],
  offers: [
    {
      id: "offer_strategy",
      whop_company_id: companyId,
      title: "Creator Strategy Session",
      slug: "creator-strategy",
      description:
        "A focused 1:1 working session to remove the biggest bottleneck in your creator business.",
      duration_minutes: 45,
      price_cents: 25000,
      currency: "usd",
      access_mode: "paid",
      status: "published",
      checkout_url: "https://whop.com/checkout/",
      requires_manual_confirmation: true,
      min_notice_hours: 24,
      max_advance_days: 60,
      buffer_before_minutes: 0,
      buffer_after_minutes: 15,
      capacity_per_slot: 1,
    },
    {
      id: "offer_audit",
      whop_company_id: companyId,
      title: "Offer & Funnel Audit",
      slug: "offer-audit",
      description:
        "Detailed review plus a private action plan for your offer, funnel, and messaging.",
      duration_minutes: 60,
      price_cents: 40000,
      currency: "usd",
      access_mode: "paid",
      status: "published",
      checkout_url: "https://whop.com/checkout/",
      requires_manual_confirmation: true,
      min_notice_hours: 48,
      max_advance_days: 45,
      buffer_before_minutes: 15,
      buffer_after_minutes: 15,
      capacity_per_slot: 1,
    },
    {
      id: "offer_member",
      whop_company_id: companyId,
      title: "Member Momentum Call",
      slug: "momentum-call",
      description:
        "A private check-in included with active Scaled Creators memberships.",
      duration_minutes: 30,
      price_cents: 0,
      currency: "usd",
      access_mode: "members_only",
      status: "published",
      checkout_url: null,
      requires_manual_confirmation: true,
      min_notice_hours: 24,
      max_advance_days: 30,
      buffer_before_minutes: 0,
      buffer_after_minutes: 15,
      capacity_per_slot: 1,
    },
  ],
  bookings: [
    {
      id: "booking_1",
      whop_company_id: companyId,
      whop_user_id: "user_avery",
      offer_id: "offer_strategy",
      coach_id: "coach_graham",
      status: "requested",
      requested_start_at: hours(28),
      requested_end_at: hours(28.75),
      confirmed_start_at: null,
      confirmed_end_at: null,
      timezone: "America/Chicago",
      intake_answers: { goal: "Launch a premium cohort" },
      member_note: "I want to pressure-test pricing.",
      admin_note: null,
      meeting_location: null,
      meeting_url: null,
      manual_join_instructions: null,
      created_at: hours(-4),
      booking_offers: {
        title: "Creator Strategy Session",
        duration_minutes: 45,
      },
    },
    {
      id: "booking_2",
      whop_company_id: companyId,
      whop_user_id: "user_demo_member",
      offer_id: "offer_audit",
      coach_id: "coach_maya",
      status: "confirmed",
      requested_start_at: hours(51),
      requested_end_at: hours(52),
      confirmed_start_at: hours(51),
      confirmed_end_at: hours(52),
      timezone: "America/Chicago",
      intake_answers: { goal: "Improve conversion" },
      member_note: null,
      admin_note: "Review landing page before session.",
      meeting_location: "Private Discord call room",
      meeting_url: null,
      manual_join_instructions:
        "Open the private coaching voice channel five minutes before start.",
      created_at: hours(-30),
      booking_offers: { title: "Offer & Funnel Audit", duration_minutes: 60 },
    },
  ],
  unavailable: [
    {
      id: "unavailable_1",
      whop_company_id: companyId,
      coach_id: null,
      offer_id: null,
      title: "Team planning week",
      reason: "Quarterly planning",
      starts_at: hours(120),
      ends_at: hours(240),
      all_day: true,
      recurrence_rule: null,
      status: "active",
    },
  ],
};
