"use client";
import { useMemo, useState } from "react";
import { Ban, Check, Clock3, Plus } from "lucide-react";
import type { AvailabilityRule, Coach } from "@/lib/types";
import { CustomCheckbox } from "@/components/custom-checkbox";
import { CustomSelect } from "@/components/custom-select";

const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
type Day = { weekday: number; enabled: boolean; startTime: string; endTime: string };
const blankDays = (): Day[] => dayNames.map((_, weekday) => ({ weekday, enabled: weekday > 0 && weekday < 6, startTime: "09:00", endTime: "17:00" }));

export function AvailabilityManager({ companyId, demo, coaches, initialRules, timezone, onAddBlackout, onRulesChange }: { companyId: string; demo: boolean; coaches: Coach[]; initialRules: AvailabilityRule[]; timezone: string; onAddBlackout: () => void; onRulesChange?: (rules: AvailabilityRule[]) => void }) {
  const [rules, setRules] = useState(initialRules); const [coachId, setCoachId] = useState<string | null>(coaches[0]?.id ?? null); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState(""); const [drafts, setDrafts] = useState<Record<string, Day[]>>({});
  const days = useMemo(() => { const result = blankDays().map((day) => ({ ...day, enabled: false })); const scoped = rules.filter((rule) => rule.coach_id === coachId && rule.offer_id === null); if (!scoped.length) return blankDays(); for (const rule of scoped) result[rule.weekday] = { weekday: rule.weekday, enabled: true, startTime: rule.start_time.slice(0, 5), endTime: rule.end_time.slice(0, 5) }; return result; }, [coachId, rules]);
  const key = coachId ?? "team"; const current = drafts[key] ?? days;
  function changeDay(weekday: number, update: Partial<Day>) { setSaved(false); setDrafts((all) => ({ ...all, [key]: current.map((day) => day.weekday === weekday ? { ...day, ...update } : day) })); }
  async function save() { setSaving(true); setError(""); try { let next: AvailabilityRule[]; if (demo) next = current.filter((day) => day.enabled).map((day) => ({ id: crypto.randomUUID(), whop_company_id: companyId, coach_id: coachId, offer_id: null, weekday: day.weekday, start_time: day.startTime, end_time: day.endTime, timezone, status: "active" })); else { const response = await fetch("/api/availability-rules", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId, coachId, timezone, days: current }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); next = payload.rules; } setRules((items) => { const merged = [...items.filter((rule) => !(rule.coach_id === coachId && rule.offer_id === null)), ...next]; onRulesChange?.(merged); return merged; }); setSaved(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save availability."); } finally { setSaving(false); } }
  const coachOptions = [{ value: "", label: "Team default" }, ...coaches.map((coach) => ({ value: coach.id, label: coach.name }))];
  return <div className="content-stack fade-in"><header className="section-page-heading"><div><p className="eyebrow">Weekly schedule</p><h2>Availability</h2><p>Choose when each coach can receive booking requests.</p></div></header><section className="panel availability-editor"><div className="panel-heading availability-heading"><div><h2>Requestable hours</h2><p>Blackouts, existing bookings, buffers, and notice periods are removed automatically.</p></div><div className="availability-coach-select"><span>Editing schedule for</span><CustomSelect value={coachId ?? ""} options={coachOptions} onChange={(value) => { setCoachId(value || null); setSaved(false); }} ariaLabel="Coach schedule"/></div></div><div className="schedule-days">{current.map((day) => <div className={`availability-edit-row ${day.enabled ? "enabled" : ""}`} key={day.weekday}><CustomCheckbox checked={day.enabled} onChange={(enabled) => changeDay(day.weekday, { enabled })} label={dayNames[day.weekday]} description={day.enabled ? "Accept requests" : "Unavailable"}/>{day.enabled && <div className="time-range"><Clock3 size={15}/><label><span>From</span><input type="time" value={day.startTime} onChange={(event) => changeDay(day.weekday, { startTime: event.target.value })}/></label><span className="time-separator">to</span><label><span>Until</span><input type="time" value={day.endTime} onChange={(event) => changeDay(day.weekday, { endTime: event.target.value })}/></label></div>}</div>)}</div>{error && <p className="form-error settings-error">{error}</p>}<div className="availability-save-row"><span className="muted">Times use {timezone}</span><button className="sc-btn-primary" onClick={save} disabled={saving}>{saving ? "Saving…" : saved ? <><Check size={16}/> Changes saved</> : "Save availability"}</button></div></section><section className="blackout-callout panel"><span className="blackout-callout-icon"><Ban size={21}/></span><div><p className="eyebrow">Exceptions</p><h3>Blackout dates</h3><p>Block vacations, travel, holidays, or any dates that should never appear to customers.</p></div><button className="sc-btn-secondary" onClick={onAddBlackout}><Plus size={16}/> Add blackout dates</button></section></div>;
}
