"use client";
import { useMemo, useState } from "react";
import { Check, Clock3 } from "lucide-react";
import type { AvailabilityRule, Coach } from "@/lib/types";

const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
type Day = { weekday: number; enabled: boolean; startTime: string; endTime: string };
const blankDays = (): Day[] => dayNames.map((_, weekday) => ({ weekday, enabled: weekday > 0 && weekday < 6, startTime: "09:00", endTime: "17:00" }));

export function AvailabilityManager({ companyId, demo, coaches, initialRules, timezone }: { companyId: string; demo: boolean; coaches: Coach[]; initialRules: AvailabilityRule[]; timezone: string }) {
  const [rules, setRules] = useState(initialRules); const [coachId, setCoachId] = useState<string | null>(coaches[0]?.id ?? null); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  const days = useMemo(() => { const result = blankDays().map((day) => ({ ...day, enabled: false })); const scoped = rules.filter((rule) => rule.coach_id === coachId && rule.offer_id === null); if (!scoped.length) return blankDays(); for (const rule of scoped) result[rule.weekday] = { weekday: rule.weekday, enabled: true, startTime: rule.start_time.slice(0, 5), endTime: rule.end_time.slice(0, 5) }; return result; }, [coachId, rules]);
  const [drafts, setDrafts] = useState<Record<string, Day[]>>({}); const key = coachId ?? "team"; const current = drafts[key] ?? days;
  function changeDay(weekday: number, patch: Partial<Day>) { setSaved(false); setDrafts((all) => ({ ...all, [key]: current.map((day) => day.weekday === weekday ? { ...day, ...patch } : day) })); }
  async function save() { setSaving(true); setError(""); try { let nextRules: AvailabilityRule[]; if (demo) nextRules = current.filter((day) => day.enabled).map((day) => ({ id: crypto.randomUUID(), whop_company_id: companyId, coach_id: coachId, offer_id: null, weekday: day.weekday, start_time: day.startTime, end_time: day.endTime, timezone, status: "active" })); else { const response = await fetch("/api/availability-rules", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId, coachId, timezone, days: current }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); nextRules = payload.rules; } setRules((items) => [...items.filter((rule) => !(rule.coach_id === coachId && rule.offer_id === null)), ...nextRules]); setSaved(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save availability."); } finally { setSaving(false); } }
  return <div className="content-stack fade-in"><section className="unavailable-hero"><div><p className="eyebrow">Weekly schedule</p><h2>Set requestable hours</h2><p>These hours are combined with blackouts, existing bookings, offer buffers, and minimum notice before customers see a time.</p></div><button className="sc-btn-primary" onClick={save} disabled={saving}>{saving ? "Saving…" : saved ? <><Check size={16}/> Saved</> : "Save hours"}</button></section><article className="panel availability-editor"><div className="panel-heading"><div><p className="eyebrow">{timezone}</p><h2>Coach schedule</h2></div><select value={coachId ?? ""} onChange={(event) => { setCoachId(event.target.value || null); setSaved(false); }}><option value="">Team default</option>{coaches.map((coach) => <option key={coach.id} value={coach.id}>{coach.name}</option>)}</select></div>{current.map((day) => <div className="availability-edit-row" key={day.weekday}><label className="day-toggle"><input type="checkbox" checked={day.enabled} onChange={(event) => changeDay(day.weekday, { enabled: event.target.checked })}/><span>{dayNames[day.weekday]}</span></label>{day.enabled ? <div className="time-range"><Clock3 size={15}/><input type="time" value={day.startTime} onChange={(event) => changeDay(day.weekday, { startTime: event.target.value })}/><span>to</span><input type="time" value={day.endTime} onChange={(event) => changeDay(day.weekday, { endTime: event.target.value })}/></div> : <span className="muted">Unavailable</span>}</div>)}{error && <p className="form-error settings-error">{error}</p>}</article></div>;
}
