"use client";
import { useState } from "react";
import { Plus, UserRound, X } from "lucide-react";
import type { Coach } from "@/lib/types";

export function CoachManager({ companyId, demo, initialCoaches }: { companyId: string; demo: boolean; initialCoaches: Coach[] }) {
  const [coaches, setCoaches] = useState(initialCoaches); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: "", bio: "", timezone: "America/Chicago" }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { let coach: Coach; if (demo) coach = { id: crypto.randomUUID(), whop_company_id: companyId, ...form, status: "active" }; else { const response = await fetch("/api/coaches", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId, ...form }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); coach = payload.coach; } setCoaches((items) => [...items, coach]); setOpen(false); setForm({ name: "", bio: "", timezone: "America/Chicago" }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not add coach."); } finally { setSaving(false); } }
  return <div className="content-stack fade-in"><section className="unavailable-hero"><div><p className="eyebrow">Your team</p><h2>Coaches & assignment</h2><p>Add the people who can deliver sessions. Assign eligible coaches on each offer, then choose the final coach on a booking before confirmation.</p></div><button className="sc-btn-primary" onClick={() => setOpen(true)}><Plus size={16}/> Add coach</button></section><div className="coach-grid">{coaches.map((coach) => <article className="coach-card panel" key={coach.id}><span className="coach-avatar"><UserRound/></span><div><span className="health-badge success">Active</span><h3>{coach.name}</h3><p>{coach.bio || "No bio yet."}</p><small>{coach.timezone}</small></div></article>)}</div>{open && <div className="modal-backdrop"><form className="modal sc-card" onSubmit={submit}><div className="panel-heading"><div><p className="eyebrow">Team member</p><h2>Add a coach</h2></div><button type="button" className="icon-button" onClick={() => setOpen(false)}><X size={18}/></button></div><div className="field"><label>Name</label><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required/></div><div className="field"><label>Bio / specialty</label><textarea value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })}/></div><div className="field"><label>Timezone</label><input value={form.timezone} onChange={(e) => setForm({ ...form, timezone: e.target.value })} required/></div>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="sc-btn-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="sc-btn-primary" disabled={saving}>{saving ? "Adding…" : "Add coach"}</button></div></form></div>}</div>;
}
