"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, Check, Clock3, LockKeyhole, MessageCircle, Sparkles, X } from "lucide-react";
import type { Booking, DashboardData, Offer } from "@/lib/types";

const money = (cents: number) => cents === 0 ? "Free" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);
const previewSlots = [2, 3, 4, 7, 8].map((days, i) => { const d = new Date(Date.now() + days * 86_400_000); d.setHours([10, 13, 15, 11, 14][i], 0, 0, 0); return d; });

export function MemberExperience({ experienceId, userId, data }: { experienceId: string; userId: string; data: DashboardData }) {
  const [view, setView] = useState<"offers" | "bookings">("offers");
  const [selected, setSelected] = useState<Offer | null>(null);
  const [bookings, setBookings] = useState(data.bookings.filter((booking) => booking.whop_user_id === userId));
  return <main className="theme-root member-shell">
    <nav className="member-nav"><div className="brand">Scaled<span>Coaching</span></div><div className="member-tabs"><button className={view === "offers" ? "active" : ""} onClick={() => setView("offers")}>Coaching</button><button className={view === "bookings" ? "active" : ""} onClick={() => setView("bookings")}>My bookings</button></div><button className="support-button"><MessageCircle size={17}/> Help</button></nav>
    {view === "offers" ? <><section className="member-hero"><div><p className="eyebrow">Private coaching</p><h1>Make your next move<br/><span className="gradient-text">the right one.</span></h1><p>Choose the support you need. Every request is personally reviewed so your session starts with the right coach and context.</p></div><div className="concierge-note"><Sparkles size={19}/><div><strong>Concierge confirmation</strong><p>You’ll see private meeting details here after your time is confirmed.</p></div></div></section>
      {data.emergencyPaused ? <div className="member-pause"><Clock3/><div><strong>New bookings are temporarily paused.</strong><p>Your existing sessions are still available under My bookings.</p></div></div> : <section className="offer-grid">{data.offers.filter((offer) => offer.status === "published").map((offer) => <article className="member-offer" key={offer.id}><div className="offer-top"><span className="offer-icon">{offer.duration_minutes}</span><span className="status-badge draft">{offer.price_cents ? "Paid coaching" : "Free coaching"}</span></div><div><h2>{offer.title}</h2><p>{offer.description}</p></div><div className="offer-details"><span><Clock3 size={16}/>{offer.duration_minutes} minutes</span><span><CalendarDays size={16}/>Manual confirmation</span></div><div className="offer-footer"><strong>{money(offer.price_cents)}</strong><button className="sc-btn-primary" onClick={() => setSelected(offer)}>{offer.price_cents ? "View & pay" : "Request a time"}<ArrowRight size={16}/></button></div></article>)}</section>}
    </> : <MyBookings experienceId={experienceId} demo={data.demo} bookings={bookings} onChange={(updated) => setBookings((items) => items.map((item) => item.id === updated.id ? updated : item))}/>}
    <footer className="member-footer"><span>Times shown in America/Chicago</span><span>Payments securely handled by Whop</span></footer>
    {selected && <BookingFlow experienceId={experienceId} offer={selected} data={data} onClose={() => setSelected(null)} />}
  </main>;
}

function MyBookings({ experienceId, demo, bookings, onChange }: { experienceId: string; demo: boolean; bookings: Booking[]; onChange: (booking: Booking) => void }) {
  const [requesting, setRequesting] = useState<string | null>(null); const [reason, setReason] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function requestRefund() { if (!requesting) return; setSaving(true); setError(""); try { const current = bookings.find((booking) => booking.id === requesting)!; if (demo) onChange({ ...current, status: "cancelled", refund_status: "requested", refund_reason: reason }); else { const response = await fetch(`/api/booking-requests/${requesting}/refund-request`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ experienceId, reason }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); onChange(payload.booking); } setRequesting(null); setReason(""); } catch (value) { setError(value instanceof Error ? value.message : "Could not request refund."); } finally { setSaving(false); } }
  return <section className="member-bookings"><p className="eyebrow">Your sessions</p><h1>My bookings</h1><div className="member-booking-list">{bookings.length === 0 && <div className="notice-empty sc-card"><CalendarDays/><strong>No sessions yet</strong><p>Choose a coaching offer when you’re ready.</p></div>}{bookings.map((booking) => <article className="member-booking-card sc-card" key={booking.id}><div><span className={`health-badge ${booking.status === "confirmed" ? "success" : "warning"}`}>{booking.refund_status && booking.refund_status !== "not_requested" ? `refund ${booking.refund_status}` : booking.status.replaceAll("_", " ")}</span><h2>{booking.booking_offers?.title}</h2><p>{booking.requested_start_at ? new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(booking.confirmed_start_at ?? booking.requested_start_at)) : "Time pending"}</p>{booking.whop_payment_id && !["requested", "processing", "refunded"].includes(booking.refund_status ?? "not_requested") && !["completed", "no_show"].includes(booking.status) && <button className="refund-link" onClick={() => setRequesting(booking.id)}>Request a refund</button>}</div>{booking.status === "confirmed" && <div className="meeting-box"><LockKeyhole size={18}/><div><strong>{booking.meeting_location || "Meeting details coming soon"}</strong><p>{booking.manual_join_instructions || "Your coach will add private joining instructions here."}</p></div></div>}</article>)}</div>
    {requesting && <div className="modal-backdrop"><div className="modal sc-card"><div className="panel-heading"><div><p className="eyebrow">Cancel & refund</p><h2>Request a refund</h2></div><button className="icon-button" onClick={() => setRequesting(null)}><X size={18}/></button></div><div className="notice"><span>Your booking is cancelled as soon as you submit. The coach will review and issue the full refund through Whop.</span></div><div className="field"><label>Reason</label><textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Tell the coach why you need a refund"/></div>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button className="sc-btn-secondary" onClick={() => setRequesting(null)}>Keep booking</button><button className="sc-btn-primary" disabled={saving || reason.trim().length < 3} onClick={requestRefund}>{saving ? "Submitting…" : "Cancel & request refund"}</button></div></div></div>}
  </section>;
}

function BookingFlow({ experienceId, offer, data, onClose }: { experienceId: string; offer: Offer; data: DashboardData; onClose: () => void }) {
  const eligibleCoaches = offer.coach_ids?.length ? data.coaches.filter((coach) => offer.coach_ids?.includes(coach.id)) : data.coaches;
  const [coachId, setCoachId] = useState(eligibleCoaches[0]?.id ?? ""); const [step, setStep] = useState(1); const [slot, setSlot] = useState(""); const [goal, setGoal] = useState(""); const [note, setNote] = useState(""); const [sent, setSent] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [slots, setSlots] = useState<Date[]>(data.demo ? previewSlots : []); const [loadingSlots, setLoadingSlots] = useState(!data.demo);
  useEffect(() => { if (data.demo) return; const query = new URLSearchParams({ experienceId, offerId: offer.id }); if (coachId) query.set("coachId", coachId); fetch(`/api/availability/slots?${query}`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error || "Could not load available times."); setSlots((body.slots as string[]).slice(0, 12).map((value) => new Date(value))); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Could not load available times.")).finally(() => setLoadingSlots(false)); }, [coachId, data.demo, experienceId, offer.id]);
  function chooseCoach(nextCoachId: string) { setCoachId(nextCoachId); setSlot(""); setError(""); if (!data.demo) setLoadingSlots(true); }
  async function submit() { if (!slot) return; setSaving(true); setError(""); try { if (!data.demo) { const response = await fetch("/api/booking-requests", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ experienceId, companyId: data.companyId, offerId: offer.id, coachId: coachId || null, startsAt: slot, timezone: "America/Chicago", intakeAnswers: { goal }, memberNote: note }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); if (body.checkoutUrl) { window.location.assign(body.checkoutUrl); return; } } setSent(true); } catch (value) { setError(value instanceof Error ? value.message : "Could not send your request."); } finally { setSaving(false); } }
  if (sent) return <div className="modal-backdrop"><div className="booking-modal sc-card success-modal"><span className="success-icon"><Check size={28}/></span><p className="eyebrow">Request received</p><h2>Your request is in.</h2><p>You’ll see confirmation details here once it’s reviewed.</p><button className="sc-btn-primary" onClick={onClose}>Back to coaching</button></div></div>;
  return <div className="modal-backdrop"><section className="booking-modal sc-card" role="dialog" aria-modal="true"><header className="booking-modal-head"><button className="icon-button" onClick={step === 1 ? onClose : () => setStep(step - 1)}>{step === 1 ? <X size={19}/> : <ArrowLeft size={19}/>}</button><div><small>Step {step} of 3</small><span className="progress-track"><i style={{ width: `${step * 33.333}%` }}/></span></div></header>
    {step === 1 && <div className="flow-content"><p className="eyebrow">Choose a time</p><h2>{offer.title}</h2>{eligibleCoaches.length > 1 && <div className="field coach-choice"><label>Preferred coach</label><select value={coachId} onChange={(event) => chooseCoach(event.target.value)}>{eligibleCoaches.map((coach) => <option key={coach.id} value={coach.id}>{coach.name}</option>)}</select></div>}{loadingSlots ? <div className="notice">Loading available times…</div> : slots.length === 0 ? <div className="notice">No request times are open right now.</div> : <div className="slot-list">{slots.map((date) => <button key={date.toISOString()} className={slot === date.toISOString() ? "active" : ""} onClick={() => setSlot(date.toISOString())}><span>{new Intl.DateTimeFormat("en-US", { weekday: "short", month: "short", day: "numeric" }).format(date)}</span><strong>{new Intl.DateTimeFormat("en-US", { hour: "numeric", minute: "2-digit" }).format(date)}</strong></button>)}</div>}{error && <p className="form-error">{error}</p>}<button className="sc-btn-primary full-button" disabled={!slot} onClick={() => setStep(2)}>Continue <ArrowRight size={16}/></button></div>}
    {step === 2 && <div className="flow-content"><p className="eyebrow">A little context</p><h2>What would make this session a win?</h2><div className="field"><label>Your main goal</label><textarea value={goal} onChange={(event) => setGoal(event.target.value)}/></div><div className="field"><label>Anything else? <span className="muted">Optional</span></label><input value={note} onChange={(event) => setNote(event.target.value)}/></div><button className="sc-btn-primary full-button" disabled={!goal.trim()} onClick={() => setStep(3)}>Review request <ArrowRight size={16}/></button></div>}
    {step === 3 && <div className="flow-content"><p className="eyebrow">Review</p><h2>Ready to send?</h2><div className="request-summary"><div><span>Session</span><strong>{offer.title}</strong></div><div><span>Preferred time</span><strong>{new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(slot))}</strong></div><div><span>Price</span><strong>{money(offer.price_cents)}{offer.price_cents ? " via Whop" : ""}</strong></div></div><div className="notice"><Sparkles size={17}/><span>{offer.price_cents ? "Payment is required before your request reaches the coach." : "This is a request, not an automatic confirmation."}</span></div>{error && <p className="form-error">{error}</p>}<button className="sc-btn-primary full-button" disabled={saving} onClick={submit}>{saving ? "Sending…" : offer.price_cents ? "Pay securely with Whop" : "Send request"}<ArrowRight size={16}/></button></div>}
  </section></div>;
}
