"use client";
import { useState } from "react";
import { Plus, X } from "lucide-react";
import type { Coach, Offer } from "@/lib/types";

export function OfferManager({ companyId, demo, initialOffers, coaches }: { companyId: string; demo: boolean; initialOffers: Offer[]; coaches: Coach[] }) {
  const [offers, setOffers] = useState(initialOffers); const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ title: "", description: "", durationMinutes: 45, pricing: "free" as "free" | "paid", amount: "", status: "published" as "published" | "draft", coachIds: [] as string[] });
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try {
    const body = { companyId, title: form.title, description: form.description, durationMinutes: form.durationMinutes, pricing: form.pricing, priceCents: form.pricing === "paid" ? Math.round(Number(form.amount) * 100) : 0, status: form.status, coachIds: form.coachIds, minNoticeHours: 24, bufferAfterMinutes: 15 };
    let offer: Offer;
    if (demo) offer = { id: crypto.randomUUID(), whop_company_id: companyId, slug: form.title.toLowerCase().replace(/\W+/g, "-"), title: form.title, description: form.description, duration_minutes: form.durationMinutes, price_cents: body.priceCents, currency: "usd", access_mode: form.pricing, status: form.status, checkout_url: null, requires_manual_confirmation: true, min_notice_hours: 24, max_advance_days: 60, buffer_before_minutes: 0, buffer_after_minutes: 15, capacity_per_slot: 1, coach_ids: form.coachIds };
    else { const response = await fetch("/api/offers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); offer = payload.offer; }
    setOffers((items) => [...items, offer]); setOpen(false); setForm({ title: "", description: "", durationMinutes: 45, pricing: "free", amount: "", status: "published", coachIds: [] });
  } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save offer."); } finally { setSaving(false); } }
  return <div className="content-stack fade-in"><section className="unavailable-hero"><div><p className="eyebrow">Products & payments</p><h2>Coaching offers</h2><p>Free offers submit immediately. Paid offers send the member to a secure one-time Whop checkout before entering your confirmation queue.</p></div><button className="sc-btn-primary" onClick={() => setOpen(true)}><Plus size={16}/> New offer</button></section><div className="card-grid">{offers.map((offer) => { const assigned = coaches.filter((coach) => offer.coach_ids?.includes(coach.id)); return <article className="offer-admin-card" key={offer.id}><div className="offer-accent"/><span className={`status-badge ${offer.status}`}>{offer.status}</span><h2>{offer.title}</h2><p>{offer.description}</p><div className="offer-meta"><span>{offer.duration_minutes} min</span><strong>{offer.price_cents ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(offer.price_cents / 100) : "Free"}</strong></div><div className="health-row"><span className="health-badge success">{offer.price_cents ? "Whop checkout" : "No payment"}</span><span className="health-badge neutral">{assigned.length ? assigned.map((c) => c.name).join(", ") : "Any coach"}</span></div></article>; })}</div>
  {open && <div className="modal-backdrop"><form className="modal sc-card" onSubmit={submit}><div className="panel-heading"><div><p className="eyebrow">New coaching product</p><h2>Create offer</h2></div><button type="button" className="icon-button" onClick={() => setOpen(false)}><X size={18}/></button></div><div className="field"><label>Offer name</label><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required/></div><div className="field"><label>Description</label><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/></div><div className="form-grid"><div className="field"><label>Duration (minutes)</label><input type="number" min="5" value={form.durationMinutes} onChange={(e) => setForm({ ...form, durationMinutes: Number(e.target.value) })}/></div><div className="field"><label>Visibility</label><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as "draft" | "published" })}><option value="published">Published</option><option value="draft">Draft</option></select></div></div><div className="field"><label>Pricing</label><div className="choice-row"><button type="button" className={form.pricing === "free" ? "active" : ""} onClick={() => setForm({ ...form, pricing: "free" })}>Free</button><button type="button" className={form.pricing === "paid" ? "active" : ""} onClick={() => setForm({ ...form, pricing: "paid" })}>Paid</button></div></div>{form.pricing === "paid" && <div className="field"><label>Amount (USD)</label><input type="number" min="0.50" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} required/></div>}<div className="field"><label>Eligible coaches</label><div className="choice-row wrap">{coaches.map((coach) => <button key={coach.id} type="button" className={form.coachIds.includes(coach.id) ? "active" : ""} onClick={() => setForm({ ...form, coachIds: form.coachIds.includes(coach.id) ? form.coachIds.filter((id) => id !== coach.id) : [...form.coachIds, coach.id] })}>{coach.name}</button>)}</div><small className="muted">Leave empty to allow any active coach.</small></div>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="sc-btn-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="sc-btn-primary" disabled={saving}>{saving ? "Creating…" : "Create offer"}</button></div></form></div>}</div>;
}
