"use client";
import { useState } from "react";
import { Check, Globe2, LifeBuoy } from "lucide-react";
import type { BookingSettings } from "@/lib/types";
import { CustomSelect } from "@/components/custom-select";
import { DEFAULT_SUPPORT_CONTACT } from "@/lib/constants";

const timezoneOptions = ["America/Chicago", "America/New_York", "America/Denver", "America/Los_Angeles", "Europe/London", "Europe/Paris", "Asia/Dubai", "Asia/Singapore", "Australia/Sydney"].map((value) => ({ value, label: value.replaceAll("_", " ") }));
export function SettingsManager({ companyId, demo, initialSettings }: { companyId: string; demo: boolean; initialSettings: BookingSettings }) {
  const [form, setForm] = useState({ defaultTimezone: initialSettings.default_timezone, supportContact: initialSettings.support_contact || DEFAULT_SUPPORT_CONTACT }); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { if (!demo) { const response = await fetch("/api/settings/pause", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId, ...form }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); } setSaved(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save settings."); } finally { setSaving(false); } }
  return <div className="content-stack settings-page fade-in"><header className="section-page-heading"><div><p className="eyebrow">Workspace</p><h2>Settings</h2><p>Configure how scheduling information appears throughout your coaching experience.</p></div></header><form className="settings-stack" onSubmit={save}><section className="panel settings-card"><div className="settings-card-icon"><Globe2 size={20}/></div><div className="settings-card-body"><div className="settings-card-heading"><h3>Regional settings</h3><p>Used for availability, booking requests, and customer-facing session times.</p></div><div className="field"><label>Default timezone</label><CustomSelect value={form.defaultTimezone} options={timezoneOptions} onChange={(value) => { setSaved(false); setForm({ ...form, defaultTimezone: value }); }} placeholder="Choose a timezone"/><small className="field-help">Individual coaches can still keep their own timezone.</small></div></div></section><section className="panel settings-card"><div className="settings-card-icon"><LifeBuoy size={20}/></div><div className="settings-card-body"><div className="settings-card-heading"><h3>Customer support</h3><p>Give customers a direct way to contact you from the coaching experience.</p></div><div className="field"><label>Support email</label><input type="email" value={form.supportContact} onChange={(event) => { setSaved(false); setForm({ ...form, supportContact: event.target.value }); }} placeholder="support@scaledcreators.com" required/><small className="field-help">This address appears in the customer Help panel.</small></div></div></section>{error && <p className="form-error action-error">{error}</p>}<div className="settings-action-bar"><div><strong>Workspace settings</strong><span>{saved ? "Your changes are live." : "Save when you’re ready."}</span></div><button className="sc-btn-primary" disabled={saving}>{saving ? "Saving…" : saved ? <><Check size={16}/> Saved</> : "Save settings"}</button></div></form></div>;
}
