"use client";
import { useState } from "react";
import { Check, Webhook } from "lucide-react";
import type { BookingSettings } from "@/lib/types";

export function SettingsManager({ companyId, demo, initialSettings }: { companyId: string; demo: boolean; initialSettings: BookingSettings }) {
  const [form, setForm] = useState({ defaultTimezone: initialSettings.default_timezone, supportContact: initialSettings.support_contact ?? "" }); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { if (!demo) { const response = await fetch("/api/settings/pause", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId, ...form }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); } setSaved(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save settings."); } finally { setSaving(false); } }
  return <div className="content-stack fade-in"><section className="unavailable-hero"><div><p className="eyebrow">Workspace</p><h2>Booking settings</h2><p>Control timezone and member support details. Payment and identity secrets remain server-only in Vercel.</p></div></section><form className="panel settings-form" onSubmit={save}><div className="panel-heading"><div><h2>General</h2><p>Used throughout availability and customer-facing booking screens.</p></div></div><div className="settings-fields"><div className="field"><label>Default timezone</label><input value={form.defaultTimezone} onChange={(event) => { setSaved(false); setForm({ ...form, defaultTimezone: event.target.value }); }} placeholder="America/Chicago"/></div><div className="field"><label>Support contact</label><input value={form.supportContact} onChange={(event) => { setSaved(false); setForm({ ...form, supportContact: event.target.value }); }} placeholder="support@example.com"/></div>{error && <p className="form-error">{error}</p>}<button className="sc-btn-primary settings-save" disabled={saving}>{saving ? "Saving…" : saved ? <><Check size={16}/> Saved</> : "Save settings"}</button></div></form><article className="panel integration-health"><Webhook/><div><strong>Whop webhook connected</strong><p><code>/webhooks/whop</code> verified with a signed payment event. Payments and refunds are processed through Whop.</p></div><span className="health-badge success">Healthy</span></article></div>;
}
